spring:
  application:
    name: auth-service
  config:
    import: optional:configserver:http://127.0.0.1:8888/

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

  profiles:
    active: local
    include:
      - redis
      - datasource
      - security
      - openfeign
      - eureka
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info,actuator